version: '3.9'

services:
  web:
    build: .
    container_name: hireme_api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["./wait-for-db.sh", "dpg-d15fo2nfte5s739612b0-a.singapore-postgres.render.com", "5432", "uvicorn", "hiremebackend.main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - db_proxy  # Dummy service to satisfy docker-compose syntax (actual DB is external)

  # Dummy service to avoid error on 'depends_on' - won't be used
  db_proxy:
    image: alpine
    command: ["tail", "-f", "/dev/null"]

volumes:
  pgdata:
